version: '3.8'

services:
  app:
    container_name: app-python3-technical_test
    image: guilhermercarvalho/app-technical_test
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3-bullseye
        NODE_VERSION: "14"
    volumes:
      - ..:/workspace:cached
    depends_on:
      - db
    network_mode: service:db
    command: sleep infinity

  db:
    container_name: db-psql-technical_test
    image: postgres:14-alpine3.14
    env_file:
      - .env/db.env
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-technical_test
    image: dpage/pgadmin4:6
    env_file:
      - .env/pgadmin.env
    depends_on:
      - db
    restart: unless-stopped
